title: "Performance Portable Design Patterns"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # You can change this to "dark", "air", etc.

# Site Settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  yntax_highlighter: rouge
  input: GFM  # GitHub Flavored Markdown

# Enable MathJax site-wide (optional, or do it per page)
mathjax: true

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
